apiVersion: v1 
kind: ConfigMap 
metadata:
  name: l2f-config
  namespace: automation
data:
  ldap2float.conf: |
    [ldap]
    url: ldap.example.com
    user_dn: uid=ldap2float,dc=example,dc=com
    user_pass: ***
    base: dc=example,dc=com
    filter: (&(objectclass=person)(email=*))
    group_dn: cn=float-users,ou=groups,dc=example,dc=com
    
    [float]
    access_token: ****
    application_name: 'ldap2float'
    contact_email: me@example.com
    # old-domain.org changed to new-domain.org for LDAP users
    email_domain_overrides: [['old-domain.org', 'new-domain.net']]
    
    [logging]
    level: INFO
    
    [conf]
    # Delete Float users this many days after their LDAP account expired 
    delete_after_days: 30
    # Maximum number of Float users to delete in one invocation
    max_users_to_delete: 5
    valid_guests: ['my_valid_float_guest@example.com']
    # The string to use when parsing date strings from ldap
    ldap_date_string: %Y%m%d00Z
